version: '3.8'
services:
  app:
    build: .       # Docker Compose sẽ tự build image từ Dockerfile trong thư mục này
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: always
